import { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Midnight Amber',
    slug: 'midnight-amber',
    price: 68,
    description: 'A captivating blend that evokes the warmth of a cozy evening. Midnight Amber combines rich amber with creamy vanilla and exotic sandalwood, creating an atmosphere of luxurious comfort. The carefully balanced fragrance opens with warm amber notes, develops into a heart of sweet vanilla, and settles into a base of smooth sandalwood.',
    shortDescription: 'Amber, Vanilla, Sandalwood',
    category: 'Signature Collection',
    fragranceFamily: 'Oriental',
    topNotes: ['Warm Amber', 'Bergamot'],
    heartNotes: ['Vanilla Bean', 'Jasmine'],
    baseNotes: ['Sandalwood', 'Musk', 'Cedar'],
    burnTime: '50 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/midnight-amber-1.jpg', '/products/midnight-amber-2.jpg'],
    inStock: true,
    rating: 4.9,
    reviewCount: 342,
    featured: true,
    bestSeller: true,
    new: false,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Rose Noir',
    slug: 'rose-noir',
    price: 75,
    description: 'An enigmatic floral masterpiece that reimagines the classic rose. Rose Noir blends precious black rose with mysterious oud and a whisper of musk, creating a sophisticated and alluring atmosphere. This is not your traditional rose—it is dark, complex, and utterly captivating.',
    shortDescription: 'Black Rose, Oud, Musk',
    category: 'Floral Series',
    fragranceFamily: 'Floral',
    topNotes: ['Black Rose', 'Saffron'],
    heartNotes: ['Oud', 'Iris'],
    baseNotes: ['White Musk', 'Amber', 'Patchouli'],
    burnTime: '55 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/rose-noir-1.jpg', '/products/rose-noir-2.jpg'],
    inStock: true,
    rating: 4.8,
    reviewCount: 256,
    featured: true,
    bestSeller: false,
    new: false,
    createdAt: new Date('2024-02-20'),
  },
  {
    id: '3',
    name: 'Cedar & Sage',
    slug: 'cedar-sage',
    price: 62,
    description: 'A grounding botanical blend inspired by ancient forests. Cedar & Sage combines the earthy warmth of red cedar with the cleansing clarity of white sage and bright bergamot. Perfect for meditation, yoga, or simply creating a sanctuary of calm in your space.',
    shortDescription: 'Cedar, White Sage, Bergamot',
    category: 'Botanical Collection',
    fragranceFamily: 'Woody',
    topNotes: ['Bergamot', 'Eucalyptus'],
    heartNotes: ['White Sage', 'Lavender'],
    baseNotes: ['Red Cedar', 'Vetiver', 'Moss'],
    burnTime: '45 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/cedar-sage-1.jpg', '/products/cedar-sage-2.jpg'],
    inStock: true,
    rating: 4.7,
    reviewCount: 189,
    featured: true,
    bestSeller: false,
    new: false,
    createdAt: new Date('2024-03-10'),
  },
  {
    id: '4',
    name: 'Golden Hour',
    slug: 'golden-hour',
    price: 85,
    description: 'Capture the magic of sunset in a candle. Golden Hour is a limited edition fragrance featuring golden honey, precious saffron, and warm woods. Each candle is hand-poured during the golden hour itself, infusing it with the energy of that magical time of day.',
    shortDescription: 'Honey, Saffron, Warm Woods',
    category: 'Limited Edition',
    fragranceFamily: 'Oriental',
    topNotes: ['Saffron', 'Orange Blossom'],
    heartNotes: ['Golden Honey', 'Ylang Ylang'],
    baseNotes: ['Sandalwood', 'Benzoin', 'Vanilla'],
    burnTime: '60 hours',
    size: '10 oz',
    weight: '340g',
    images: ['/products/golden-hour-1.jpg', '/products/golden-hour-2.jpg'],
    inStock: true,
    rating: 5.0,
    reviewCount: 87,
    featured: true,
    bestSeller: true,
    new: true,
    createdAt: new Date('2024-06-01'),
  },
  {
    id: '5',
    name: 'Velvet Rose',
    slug: 'velvet-rose',
    price: 72,
    description: 'A romantic celebration of the world most beloved flower. Velvet Rose layers damask rose with soft peony and a delicate musk finish. The result is feminine, elegant, and timelessly beautiful—like a bouquet that never fades.',
    shortDescription: 'Damask Rose, Peony, Musk',
    category: 'Floral Series',
    fragranceFamily: 'Floral',
    topNotes: ['Damask Rose', 'Pink Pepper'],
    heartNotes: ['Peony', 'Magnolia'],
    baseNotes: ['White Musk', 'Cashmere Wood'],
    burnTime: '50 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/velvet-rose-1.jpg', '/products/velvet-rose-2.jpg'],
    inStock: true,
    rating: 4.8,
    reviewCount: 256,
    featured: false,
    bestSeller: true,
    new: false,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '6',
    name: 'Fireside',
    slug: 'fireside',
    price: 65,
    description: 'Bring the warmth of a crackling fire into your home. Fireside captures the essence of an evening by the hearth with notes of smoky wood, rich cedar, and supple leather. Close your eyes and you can almost hear the flames dancing.',
    shortDescription: 'Smoky Wood, Cedar, Leather',
    category: 'Signature Collection',
    fragranceFamily: 'Woody',
    topNotes: ['Smoke', 'Black Pepper'],
    heartNotes: ['Cedar', 'Clove'],
    baseNotes: ['Leather', 'Tobacco', 'Amber'],
    burnTime: '50 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/fireside-1.jpg', '/products/fireside-2.jpg'],
    inStock: true,
    rating: 4.9,
    reviewCount: 418,
    featured: false,
    bestSeller: true,
    new: false,
    createdAt: new Date('2024-02-05'),
  },
  {
    id: '7',
    name: 'Ocean Breeze',
    slug: 'ocean-breeze',
    price: 58,
    description: 'Escape to the seaside with this refreshing aquatic fragrance. Ocean Breeze blends sea salt with crisp cucumber and soft driftwood, creating an atmosphere of coastal tranquility. Perfect for bringing a sense of calm and freshness to any room.',
    shortDescription: 'Sea Salt, Cucumber, Driftwood',
    category: 'Fresh Collection',
    fragranceFamily: 'Fresh',
    topNotes: ['Sea Salt', 'Ozone'],
    heartNotes: ['Cucumber', 'Water Lily'],
    baseNotes: ['Driftwood', 'White Cedar', 'Musk'],
    burnTime: '45 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/ocean-breeze-1.jpg', '/products/ocean-breeze-2.jpg'],
    inStock: true,
    rating: 4.6,
    reviewCount: 145,
    featured: false,
    bestSeller: false,
    new: false,
    createdAt: new Date('2024-03-25'),
  },
  {
    id: '8',
    name: 'Lavender Dreams',
    slug: 'lavender-dreams',
    price: 55,
    description: 'Drift into peaceful slumber with this calming lavender blend. Lavender Dreams combines French lavender with chamomile and soft vanilla, creating the perfect atmosphere for relaxation and rest. Ideal for bedrooms and meditation spaces.',
    shortDescription: 'French Lavender, Chamomile, Vanilla',
    category: 'Botanical Collection',
    fragranceFamily: 'Fresh',
    topNotes: ['French Lavender', 'Eucalyptus'],
    heartNotes: ['Chamomile', 'Tonka Bean'],
    baseNotes: ['Vanilla', 'Sandalwood', 'Musk'],
    burnTime: '45 hours',
    size: '8 oz',
    weight: '280g',
    images: ['/products/lavender-dreams-1.jpg', '/products/lavender-dreams-2.jpg'],
    inStock: true,
    rating: 4.7,
    reviewCount: 203,
    featured: false,
    bestSeller: false,
    new: false,
    createdAt: new Date('2024-04-10'),
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.bestSeller)
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.new)
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category.toLowerCase() === category.toLowerCase())
}

export function getProductsByFragranceFamily(family: string): Product[] {
  return products.filter((p) => p.fragranceFamily.toLowerCase() === family.toLowerCase())
}
